camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  lock-duration: 10000
subscriptions:
    notification:
      include-extension-properties: true
      variable-names: content

logging.level.org.camunda.bpm.client: DEBUG # increase the log level of the application

